<?php
/**
 * @file
 * This module uses JoliTypo to alleviate the pain of reading non correctly formatted text on Drupal.
 */

/**
 * implements hook_libraries_info to declare xautoload lib
 * @return mixed
 */
function jolitypo_libraries_info() {
  $libraries['jolitypo'] = array(
    'name' => 'jolitypo',
    'vendor url' => 'https://github.com/jolicode/JoliTypo',
    'download url' => 'https://github.com/jolicode/JoliTypo/archive/v0.1.4.tar.gz',
    'version' => '0.1.4',
    'xautoload' => function ($adapter) {
      $adapter->add('JoliTypo', 'JoliTypo-0.1.4/src');
    },
  );
  $libraries['hyphenator'] = array(
    'name' => 'hyphenator',
    'vendor url' => 'https://github.com/heiglandreas/Org_Heigl_Hyphenator',
    'download url' => 'https://github.com/heiglandreas/Org_Heigl_Hyphenator/archive/v2.0.3.tar.gz',
    'version' => '2.0.3',
    'xautoload' => function ($adapter) {
      $adapter->add('Org', 'Org_Heigl_Hyphenator-2.0.3/src');
    },
  );

  return $libraries;
}

/**
 * Implements hook_menu to add settings page
 */
function jolitypo_menu() {
  $items['admin/config/jolitypo'] = array(
    'title' => 'Jolitypo',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jolitypo_admin_settings'),
    'access arguments' => array('access administration pages'),
    'file' => 'jolitypo.admin.inc',
    'file path' => drupal_get_path('module', 'jolitypo'),
  );

  return $items;
}

/**
 * implements hook_node_presave
 */
function jolitypo_node_presave($node) {
  //$wrapper = entity_metadata_wrapper('node', $node);
  //$fixer = new JoliTypo\Fixer(array('Ellipsis', 'Dimension', 'Dash', 'CurlyQuote', 'Trademark', 'Hyphen'));

  /*$body = array(
    'summary' => $fixer->fix($wrapper->body->value()['summary']),
    'value' => $fixer->fix($wrapper->body->value()['value']),
    'format' => $fixer->fix($wrapper->body->value()['format']),
  );
  $wrapper->body->set($body);

  $wrapper->body->value()['value'] = $fixer->fix($wrapper->body->value()['value']);
  $wrapper->body->value()['summary'] = $fixer->fix($wrapper->body->value()['summary']);*/
}

/**
 * implements hook_field_formatter_info
 * @return array
 */
function jolitypo_field_formatter_info() {
  return array(
    'jolitypo_formatter' => array(
      'label' => t('JoliTypo'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
    ),
  );
}

/**
 * implements hook_field_formatter_view
 * @param $entity_type
 * @param $entity
 * @param $field
 * @param $instance
 * @param $langcode
 * @param $items
 * @param $display
 * @return array
 */
function jolitypo_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $fixerparams = variable_get('jolitypo_' . $entity->language);
  unset($fixerparams[0]);

  $fixer = new JoliTypo\Fixer($fixerparams);
  //TODO improve locale detection with associative array for IETF correspondance
  $fixer->setLocale($entity->language . '_' . strtoupper($entity->language));
  $fixed = $fixer->fix($items[0]['safe_value']);
  $element[0]['#markup'] = $fixed;

  return $element;
}

//TODO add a drush command to get the repo for jolitypo and hyphenator